package pizzastore.android;

import core.CentralTracker;
import core.PizzaStoreFacade;
import core.PizzaStoreFacadeInterface;
import android.os.Bundle;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.view.Menu;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;

public class PizzaKioskActivity extends Activity {
	
	private static PizzaStoreFacadeInterface store;
	private static String username;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        store = new PizzaStoreFacade(new CentralTracker(), true);
        
        //TODO: figure out how to move this to onclick method for button
        //TODO: better variable names (these are autogenerated right now)
        final Button button = (Button) findViewById(R.id.button1);
        final Context context = this;
        button.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
            	Intent intent = new Intent(context, NewUserActivity.class);
                startActivity(intent); 
            }
        });
       
       
        final Button button2 = (Button) findViewById(R.id.button2);
        button2.setOnClickListener(new View.OnClickListener() {
        	
            public void onClick(View v) {
            	username = ((EditText) findViewById(R.id.editText1)).getText().toString();
                if(!store.customerExists(username)){
            		AlertDialog.Builder alertDialogBuilder = new AlertDialog.Builder(
            				context);
             
            			// set dialog message
            			alertDialogBuilder
            				.setMessage("User '" + username + "' does not exist.")
            				.setCancelable(false)
            				.setNegativeButton("Ok",new DialogInterface.OnClickListener() {
            					public void onClick(DialogInterface dialog,int id) {
            						// if this button is clicked, just close
            						// the dialog box and do nothing
            						dialog.cancel();
            					}
            				});
             
            				// create alert dialog
            				AlertDialog alertDialog = alertDialogBuilder.create();
             
            				// show it
            				alertDialog.show();
                }
                else{
                	BaseActivity.setCustomer(username);
                	Intent intent = new Intent(context, ExistingUserMainActivity.class);
                    startActivity(intent); 
                }
            }
        });
        
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.activity_main, menu);
        return true;
    }
    
    public static PizzaStoreFacadeInterface getStore(){
    	return store;
    }


}
